src/vivarium_gates_nutrition_optimization_child/components/maternal_characteristics.py, src/vivarium_gates_nutrition_optimization_child/components/observers.py, src/vivarium_gates_nutrition_optimization_child/model_specifications/branches/scenarios.yaml, src/vivarium_gates_nutrition_optimization_child/model_specifications/nutrition_optimization_child.yaml
- *Category*: feature
- *JIRA issue*: [MIC-3495](https://jira.ihme.washington.edu/browse/MIC-3495)
IV iron is no longer in the model.
Ran for a few time steps.
=> remove iv iron

CHANGELOG.rst
=> update 0.1.0 CHANGELOG

src/vivarium_gates_nutrition_optimization_child/components/maternal_characteristics.py
=> fix typing

src/vivarium_gates_nutrition_optimization_child/constants/results.py, src/vivarium_gates_nutrition_optimization_child/results_processing/process_results.py
- *Category*: processing
- *JIRA issue*: [MIC-4431](https://jira.ihme.washington.edu/browse/MIC-4431)
Use new child_scenario and maternal_scenario columns instead of scenario.
Made results.
=> model 1.1 processing

CHANGELOG.rst, src/vivarium_gates_nutrition_optimization_child/__about__.py
##Model 2 V&V
- *Category*: 
release
update changelog for Model 2.0
N/A
=> Model 2 V&V

src/vivarium_gates_nutrition_optimization_child/constants/data_keys.py, src/vivarium_gates_nutrition_optimization_child/constants/paths.py, src/vivarium_gates_nutrition_optimization_child/data/loader.py
- *Category*: artifact
- *JIRA issue*: [MIC-4434](https://jira.ihme.washington.edu/browse/MIC-4434)
- *Research reference*: [modeling strategy](https://vivarium-research.readthedocs.io/en/latest/models/risk_exposures/child_growth_failure/underweight/index.html#vivarium-modeling-strategy)
Add underweight categories and exposure to artifact.
Made artifact and ran sim for a few time steps.
=> model 4 artifact

src/vivarium_gates_nutrition_optimization_child/model_specifications/nutrition_optimization_child.yaml
- *Category*: 
observers
- *JIRA issue*: [MIC-4507](https://jira.ihme.washington.edu/browse/MIC-4507)
https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.html
Model 5.0 needs `wasting_state` stratifications on mortality and cause models
Sim Runs with additions, will check output before merge
=> Model 5.0 Observers

CHANGELOG.rst, src/vivarium_gates_nutrition_optimization_child/model_specifications/nutrition_optimization_child.yaml
- *JIRA issue*: [MIC-4516](https://jira.ihme.washington.edu/browse/MIC-4516)
- *Research reference*: [PR with new data](https://github.com/ihmeuw/vivarium_research/pull/1318/files)
Use new input data from RT.
Shared results of parallel run with RT.
=> updated underweight data

src/vivarium_gates_nutrition_optimization_child/components/fertility.py, src/vivarium_gates_nutrition_optimization_child/constants/data_values.py, src/vivarium_gates_nutrition_optimization_child/constants/scenarios.py, src/vivarium_gates_nutrition_optimization_child/model_specifications/nutrition_optimization_child.yaml
- *Category*: cleanup
- *JIRA issue*: [MIC-4457](https://jira.ihme.washington.edu/browse/MIC-4457)
- *Research reference*: N/A
Remove references to SAM_K scenario.
Remove variables in data_values that are no longer used.
Ran sim for a few steps with and without removals and verified that the sim outputs I checked were exactly the same (YLDs and YLLs).
=> remove sam k scenario

src/vivarium_gates_nutrition_optimization_child/model_specifications/nutrition_optimization_child.yaml
Add treatment effects.
Ran for a few time steps.
=> add MAM and SAM treatment effects

src/vivarium_gates_nutrition_optimization_child/data/loader.py
=> use correct function name

src/vivarium_gates_nutrition_optimization_child/constants/data_keys.py, src/vivarium_gates_nutrition_optimization_child/constants/data_values.py, src/vivarium_gates_nutrition_optimization_child/constants/paths.py, src/vivarium_gates_nutrition_optimization_child/data/loader.py, src/vivarium_gates_nutrition_optimization_child/data/raw/sqlns_risk_ratios/ethiopia.csv, src/vivarium_gates_nutrition_optimization_child/utilities.py
- *Category*: artifact
- *JIRA issue*: [MIC-4501](https://jira.ihme.washington.edu/browse/MIC-4501)
- *Research reference*: [data in tables](https://vivarium-research.readthedocs.io/en/latest/models/intervention_models/lipid_based_nutrient_supplements/index.html#affected-outcomes)
Add SQLNS risk ratios key to artifact. 
Add input data and process for artifact.
Remade artifact.
=> model 7 artifact

src/vivarium_gates_nutrition_optimization_child/components/__init__.py, src/vivarium_gates_nutrition_optimization_child/components/treatment.py, src/vivarium_gates_nutrition_optimization_child/constants/data_keys.py, src/vivarium_gates_nutrition_optimization_child/constants/data_values.py, src/vivarium_gates_nutrition_optimization_child/constants/paths.py, src/vivarium_gates_nutrition_optimization_child/data/loader.py, src/vivarium_gates_nutrition_optimization_child/data/raw/sqlns_risk_ratios/ethiopia.csv, src/vivarium_gates_nutrition_optimization_child/model_specifications/nutrition_optimization_child.yaml, src/vivarium_gates_nutrition_optimization_child/utilities.py
- *Category*: implementation
- *JIRA issue*: [MIC-4502](https://jira.ihme.washington.edu/browse/MIC-4502)
- *Research reference*: [modeling strategy](https://vivarium-research.readthedocs.io/en/latest/models/intervention_models/lipid_based_nutrient_supplements/index.html#vivarium-modeling-strategy)
Add SQLNSTreatment component.
The component is mostly copied straight over from CIFF SAM. The differences are 
- how risk ratios are defined in setup using self.get_risk_ratios
- calling these ratios with index in the modifier functions
Ran simulation for a few time steps. Initialized populations at different ages and verified that lookup table was interpolating correctly. Checked that transition rates were being affected when including treatment component.
=> model 7 implementation

src/vivarium_gates_nutrition_optimization_child/components/__init__.py, src/vivarium_gates_nutrition_optimization_child/components/observers.py, src/vivarium_gates_nutrition_optimization_child/components/treatment.py, src/vivarium_gates_nutrition_optimization_child/constants/data_keys.py, src/vivarium_gates_nutrition_optimization_child/constants/data_values.py, src/vivarium_gates_nutrition_optimization_child/constants/paths.py, src/vivarium_gates_nutrition_optimization_child/data/loader.py, src/vivarium_gates_nutrition_optimization_child/data/raw/sqlns_risk_ratios/ethiopia.csv, src/vivarium_gates_nutrition_optimization_child/model_specifications/nutrition_optimization_child.yaml, src/vivarium_gates_nutrition_optimization_child/utilities.py
- *Category*: observers
- *JIRA issue*: [MIC-4503](https://jira.ihme.washington.edu/browse/MIC-4503)
- *Research reference*: [model 7 output specifications](https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.html#id12)
Use more granular age bins.
Ran sim for a time step and checked that we were stratifying by the desired age bins.
=> model 7 observers

src/vivarium_gates_nutrition_optimization_child/data/loader.py
- *JIRA issue*: [MIC-4527](https://jira.ihme.washington.edu/browse/MIC-4527)
Add wasting transition rates of 0 for ages less than 6 months.
Remade artifact key and checked that artifact looked as expected.
=> Add younger ages to wasting transition rates

CHANGELOG.rst, src/vivarium_gates_nutrition_optimization_child/__about__.py
=> model 6 changelog

src/vivarium_gates_nutrition_optimization_child/components/__init__.py, src/vivarium_gates_nutrition_optimization_child/components/observers.py, src/vivarium_gates_nutrition_optimization_child/model_specifications/branches/scenarios.yaml, src/vivarium_gates_nutrition_optimization_child/model_specifications/nutrition_optimization_child.yaml
- *Category*: runs
- *JIRA issue*: [MIC-4547](https://jira.ihme.washington.edu/browse/MIC-4547)
- *Research reference*: [model 8 output specifications](https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.html#id13)
Add mortality hazard rate observer.
Don't observer wasting person time and only observe incident transitions.
Remove unnecessary observers and age stratification.
Ran sim for a few time steps and checked output against desired outputs.
=> model 8 runs

setup.py
- *Category*: feature
- *JIRA issue*: [MIC-4582](https://jira.ihme.washington.edu/browse/MIC-4582)
split data and cluster install requirements
Successfully installed using all 4 options in different environments.
=> split data and cluster install requirements

src/vivarium_gates_nutrition_optimization_child/components/observers.py, src/vivarium_gates_nutrition_optimization_child/components/wasting.py, src/vivarium_gates_nutrition_optimization_child/constants/data_values.py, src/vivarium_gates_nutrition_optimization_child/constants/scenarios.py, src/vivarium_gates_nutrition_optimization_child/model_specifications/branches/scenarios.yaml
- *Category*: feature
- *JIRA issue*: [MIC-4584](https://jira.ihme.washington.edu/browse/MIC-4584)
- *Research reference*: [PR](https://github.com/ihmeuw/vivarium_research/pull/1349/files)
Add different logic to treatment exposure if we're in a MAM targeting scenario.
Add new scenario.
Add underweight stratification. 
Used breakpoint to verify desired simulants were being given MAM treatment.
=> MAM targeting 

src/vivarium_gates_nutrition_optimization_child/components/wasting.py, src/vivarium_gates_nutrition_optimization_child/data/loader.py, src/vivarium_gates_nutrition_optimization_child/model_specifications/nutrition_optimization_child.yaml
- *JIRA issue*: [MIC-4595](https://jira.ihme.washington.edu/browse/MIC-4595)
Exposure values should be 1 for cat1 rather than all 0s. 
Update artifact path.
Ran previously failing simulation.
=> model 10 wasting treatment exposure bug fix

src/vivarium_gates_nutrition_optimization_child/components/observers.py, src/vivarium_gates_nutrition_optimization_child/model_specifications/branches/scenarios.yaml, src/vivarium_gates_nutrition_optimization_child/model_specifications/nutrition_optimization_child.yaml
- *Category*: runs
- *JIRA issue*: [MIC-4629](https://jira.ihme.washington.edu/browse/MIC-4629)
- *Research reference*: [scenarios](https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.html#id16) and [outputs](https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.html#id17)
Update scenarios and observations/stratifications. 
Ran sim for two time steps and compared output to tables in research reference.
=> model 11 run parameters

src/vivarium_gates_nutrition_optimization_child/model_specifications/branches/scenarios.yaml, src/vivarium_gates_nutrition_optimization_child/model_specifications/nutrition_optimization_child.yaml
- *Category*: runs
- *JIRA issue*: [MIC-4610](https://jira.ihme.washington.edu/browse/MIC-4610)
- *Research reference*: [run PR](https://github.com/ihmeuw/vivarium_research/pull/1387/files)
Updates to scenarios and stratifications.
Ran sim for one time step and checked outputs.
=> model 10.2 runs

src/vivarium_gates_nutrition_optimization_child/components/wasting.py, src/vivarium_gates_nutrition_optimization_child/data/loader.py
- *JIRA issue*: [MIC-4629](https://jira.ihme.washington.edu/browse/MIC-4629)
The old code was a placeholder while testing (and actually didn't work properly either). Properly make sure no simulants under 6 months are on treatment. 
Made artifact.
=> wasting treatment exposure artifact bugfix

src/vivarium_gates_nutrition_optimization_child/data/builder.py, src/vivarium_gates_nutrition_optimization_child/tools/cli.py, src/vivarium_gates_nutrition_optimization_child/tools/make_artifacts.py
- *Category*: Feature
- *JIRA issue*: [MIC-5018](https://jira.ihme.washington.edu/browse/MIC-5018)
-Allows user to provide flag if they want to build a national level artifact instead of a subnational artifact (the default behavior)
=> Mic-5018/Click subnational artifact

src/vivarium_gates_nutrition_optimization_child/constants/metadata.py, src/vivarium_gates_nutrition_optimization_child/data/loader.py
- *Category*: Data artifact
- *JIRA issue*: [MIC-5107](https://jira.ihme.washington.edu/browse/MIC-5107)
Fixes argument to get_measure
Successfully made artifact
=> Mic-5107/Change year arg

.zenodo.json, README.rst
Files from Archiving that SHOULD be merged
Files from Archiving that SHOULD be merged
- *Category*: Other/misc 
- Updating the ORCID id file and the README.rst
=> Files from Archiving that SHOULD be merged

.github/workflows/build.yml, src/vivarium_gates_nutrition_optimization_child/components/__init__.py, src/vivarium_gates_nutrition_optimization_child/components/distribution.py, src/vivarium_gates_nutrition_optimization_child/components/maternal_characteristics.py, src/vivarium_gates_nutrition_optimization_child/components/risk.py, src/vivarium_gates_nutrition_optimization_child/components/wasting.py
- *Category*: refactor
- *JIRA issue*: https://jira.ihme.washington.edu/browse/MIC-5076
Support updated version of VPH risks 
Successfully ran the simulation. Didn't check the validity of the outputs.
=> refactor to support risk and risk effect refactors

src/vivarium_gates_nutrition_optimization_child/components/observers.py, src/vivarium_gates_nutrition_optimization_child/components/population.py, src/vivarium_gates_nutrition_optimization_child/model_specifications/branches/scenarios.yaml, src/vivarium_gates_nutrition_optimization_child/model_specifications/nutrition_optimization_child.yaml, src/vivarium_gates_nutrition_optimization_child/results_processing/process_results.py
Updates to run model 16
Updates to run model 16
- *Category*: Implementation
- *Research reference*: [](https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_nutrition_optimization/kids/concept_model.html#wave-iii)
- Runs in listed subnational locations 
- Has flexibility to include an "All" option which runs "nationally" with all locations 
- Model spec updates 
- Results processing updates
- Did a simulate and psimulate run that made results and the outputs had expected columns for both "All" and listed subnational locations
=> Updates to run model 16

creator.sh
=> Update branch name

environment.sh
- *Category*: Feature
- *JIRA issue*: [MIC-5176](https://jira.ihme.washington.edu/browse/MIC-5176)
-check if environment is a week old and delete and remake environment if it is older than a week old
=> Mic-5176/check creation time

environment.sh
=> Close if block

.github/workflows/build.yml
- *Category*: CI
- *JIRA issue*: [MIC-5209](https://jira.ihme.washington.edu/browse/MIC-5209)
- Don't install upstream dependencies inside package directory 
Tests pass
=> don't install upstream dependencies inside package directory

environment.sh
- *Category*: Feature
- *JIRA issue*: [MIC-5177](https://jira.ihme.washington.edu/browse/MIC-5177)
Check if vivarium packages have recent pushes and update environment as necessary
=> Mic 5177/check packages

src/vivarium_gates_nutrition_optimization_child/components/observers.py, src/vivarium_gates_nutrition_optimization_child/model_specifications/nutrition_optimization_child.yaml
- *Category*:  feature
- *JIRA issue*: https://jira.ihme.washington.edu/browse/MIC-5163
This excludes results we don't care about. Note that there are a few
changes needed along the way to do that.
I ran some small simulations against the maternal
and child models.
=> exclude unwanted results

.flake8, Jenkinsfile, Makefile, pyproject.toml, setup.py
- *Category*: CI
- *JIRA issue*: [MIC-XYZ](https://jira.ihme.washington.edu/browse/MIC-5182)
-add files for Jenkins pipeline
Successful jenkins build
=> Mic 5182/jenkins files

environment.sh
- *Category*: Bugfix
- *JIRA issue*: [MIC-5276](https://jira.ihme.washington.edu/browse/MIC-5276)
-fixes conda deactivate command to not have argument
-fixes way to find environment history file
Successfully built/activated environments locally and on the cluster
=> Mic-5276/bugfix/creation-script

environment.sh
=> Mic-5310/Add new flag for creation script

src/vivarium_gates_nutrition_optimization_child/components/treatment.py
- *JIRA issue*: [MIC-5328](https://jira.ihme.washington.edu/browse/MIC-5328)
Only use GHI in targeted SQ-LNS scenarios.
Put breakpoint in simulation and checked scenario 3 was full coverage and scenario 9 was partial (about 30% coverage).
=> untargeted sqlns bugfix

Jenkinsfile
=> Update slack channel

.github/workflows/build.yml
=> Add python version as arguemnt

Jenkinsfile, Makefile, setup.py
- *Category*: 
CI
- *JIRA issue*: [MIC-5797](https://jira.ihme.washington.edu/browse/MIC-5797)
=> Use Shared Makefiles
